blog/urls.py
from django.urls import path

from core.views import HomeView
from .views import  BlogDetailView, BlogListView,BlogListViewEven

app_name="blog"

urlpatterns = [
    path('<int:pk>/',BlogDetailView.as_view(), name="detail"),
    path('hoteles/',BlogListView.as_view(),name="hotel"),
    path('indx/',BlogListViewEven.as_view(), name="home")
      
]

core/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import HomeView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),


    path('blog/',include('blog.urls',namespace='blog'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
#from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.conf import settings
from django.db.models.fields.related import ManyToManyField

User = get_user_model()
# Create your models here.
def user_directory_path(instance,filename):
    return 'blog/{0}/{1}'.format(instance.nombre,filename)


def event_directory_path(instance, filename):
    return 'courses/{0}/{1}'.format( instance.evn1, filename)
 

class Hotel(models.Model):
    nombre = models.CharField(max_length=20, help_text="Nombre del Hotel",null=False)
    own = models.ForeignKey(User,on_delete=models.CASCADE,help_text="Hotel admin",null=False)
    descripcion = models.CharField(max_length=100,help_text="Breve informacion")
    thumbnail = models.ImageField(upload_to=user_directory_path,blank=True,null=True)


    def __str__(self):
        return 'Hotel: '+self.nombre+' Dueño: '+ str(self.own)


class Eventos(models.Model):
    EVENT1='1'
    EVENT2='2'
    EVENT3='3'

    EV_HOT = (
        (EVENT1,'HIKING'),
        (EVENT2,'MOTOCR'),
        (EVENT3,'CAMPING'),
    )
    resp = models.ForeignKey(Hotel,on_delete=models.CASCADE,help_text="hotel : ",null=False)
    evn1 = models.CharField(max_length=10,choices=EV_HOT,help_text="Evento 1: ")
    descripcion = models.CharField(max_length=200,help_text="Breve informacion")
    thumbnail = models.ImageField(upload_to=event_directory_path,blank=True,null=True)


class customer(models.Model):
    name = models.CharField(max_length=30,null=False)
    last_name = models.CharField(max_length=30,null= False)
    def __str__(self):
        return 'Nombre : '+ self.name + ' Apellido : '+self.last_name


    
class Room(models.Model):
    ROOM = '1'
    ROOM2 = '2'
    ROOM3 = '4'

    CAPACITY_ROOM = (
        (ROOM,'1Bed'),
        (ROOM2,'2Bed'),
        (ROOM3,'3Bed'),
    )

    custom = ManyToManyField(customer,help_text="Nombre del huesped")
    number = models.IntegerField(help_text="Numero de habitacion")
    capacity = models.CharField(max_length=10,choices=CAPACITY_ROOM,default='1',blank=True,help_text="Numero de Camas")
    descripcion = models.CharField(max_length=100,help_text="Breve informacion")
    resposable = models.ForeignKey(Hotel,on_delete=models.CASCADE,help_text="Hotel admin")
    e1 = models.ForeignKey(Eventos,on_delete=models.CASCADE,related_name='E1',default='1',help_text="EVENTO 1")
    e2 = models.ForeignKey(Eventos,on_delete=models.CASCADE,related_name='E2',default='2',help_text="EVENTO 1")
    e3 = models.ForeignKey(Eventos,on_delete=models.CASCADE,related_name='E3',default='3',help_text="EVENTO 1")
    check_in = models.DateTimeField()
    check_out = models.DateTimeField()

    def __str__(self):
        return 'Habitacion '+ str(self.number)+' Cliente: '+str(self.custom)+' Hotel: '+ str(self.resposable )




#class Booking(models.Model):
 #  usuario = models.ForeignKey(User,on_delete=models.CASCADE)

blog/views.py
from django.shortcuts import render,get_object_or_404
from django.views.generic import View

from blog.models import Hotel,Eventos

# Create your views here.

class BlogListView(View):
    def get(self,request,*args, **kwargs):
        posts = Hotel.objects.all()

        context={
            'posts':posts
        }
        return render (request, 'blog_list.html' ,context)


class HomeI(View):
    def get(self,request,*args, **kwargs):
        context={

        }
        return render (request, 'index.html',context)

class BlogDetailView(View):

    def get(self, request, pk, *args, **kwargs):
        post = get_object_or_404(Hotel, pk=pk)
        context={
            'post':post
        }
        return render(request, 'blog_detail.html', context)


class BlogListViewEven(View):
    def get(self,request,*args, **kwargs):
        posts = Eventos.objects.all()

        context={
            'posts':posts
        }
        return render (request, 'index.html' ,context)

core/views.py
from django.views.generic import View
from django.shortcuts import render

from blog.models import Eventos

class HomeView(View):
    def get(self,request,*args, **kwargs):
        event = Eventos.objects.all()
        context={
                'event':event
        }
        return render(request,'index.html',context)

templates/base.html
{% load static tailwind_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    

{% block title %}<title>Document</title>{% endblock title %}

{% block extra_head %}{% endblock extra_head %}

{% tailwind_css %}

<!--Favicon-->
<link rel="shortcut icon" type="image/x-icon" href="{% static 'img/logo.png' %}">

<!--Alpine JS-->
<script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.8.2/dist/alpine.min.js" defer></script>
<!--Boxicons-->
<link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
<!--Stripe-->
<script src="https://js.stripe.com/v3/"></script>
</head>
<body class="bg-[url('/img/hero-pattern.svg')]">
    {% block navbar %}{% endblock navbar %}
        {% comment %} nos permite enviar informaciomn de fomra dinamica {% endcomment %}
    {% block content %}{% endblock content %}
    
    {% block footer %}{% endblock footer %}

    {% block javascript %}{% endblock javascript %}

</body>
</html>

templates/blog_detail.html
{% extends 'base.html' %}
{% block title %}{% endblock title %}
{% block extra_head %}{% endblock extra_head %}




{% block navbar %}
{% include 'components/navbar.html' %}
{% endblock navbar %}




{% block content %}
lista de los detalles de la compra del usuario





a partiir de aqui es codigo basura


<!--
  This example requires Tailwind CSS v2.0+ 
  
  This example requires some changes to your config:
  
  ```
  // tailwind.config.js
  module.exports = {
    // ...
    plugins: [
      // ...
      require('@tailwindcss/aspect-ratio'),
    ],
  }
  ```
-->
<div class="bg-gray-100">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="max-w-2xl mx-auto py-16 sm:py-24 lg:py-32 lg:max-w-none">
        <h2 class="text-2xl font-extrabold text-gray-900">Collections</h2>
  
        <div class="mt-6 space-y-12 lg:space-y-0 lg:grid lg:grid-cols-3 lg:gap-x-6">
          <div class="group relative">
            <div class="relative w-full h-80 bg-white rounded-lg overflow-hidden group-hover:opacity-75 sm:aspect-w-2 sm:aspect-h-1 sm:h-64 lg:aspect-w-1 lg:aspect-h-1">
              <img src="{{post.thumbnail.url}}" alt="Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug." class="w-full h-full object-center object-cover">
            </div>
            <h3 class="mt-6 text-sm text-gray-500">
              <a href="#">
                <span class="absolute inset-0"></span>
                Dueño 
              </a>
            </h3>
            <p class="text-base font-semibold text-gray-900">{{post.nombre}}</p>
          </div>

          <div>
            <h3 class="mt-6 text-sm text-gray-500">
                <a href="#">
                  <span class="absolute inset-0"></span>
                  {{post.descripcion}} 
                </a>
              </h3>

          </div>
          
  
         
        </div>
      </div>
    </div>
  </div>
  




  <br>
  <br><br>
{% endblock content %}



{% block footer %}
{% include 'components/footer.html'%}
{% endblock footer %}



{% block javascript %}{% endblock javascript %}

templates/blog_list.html
{% extends 'base.html' %}

{% block title %}{% endblock title %}

{% block extra_head %}{% endblock extra_head %}


{% block navbar %}
{% include 'components/navbar.html' %}
{% endblock navbar %}


{% block content %}

  <section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto">
      <div class="flex flex-wrap w-full mb-8">
        <div class="w-full mb-6 lg:mb-0">
          <h1 class="sm:text-4xl text-5xl font-bold font-medium title-font mb-2 text-gray-900">Lista Hoteles</h1>
          <div class="h-1 w-20 bg-indigo-500 rounded"></div>
        </div>
      </div>
      <div class="flex flex-wrap -m-4">

        {%for post in posts%}

        <div class="lg:w-1/4 p-4 w-1/2">
          <a class="block relative h-48 rounded overflow-hidden">
            <img alt="ecommerce" class="object-cover object-center w-full h-full block" src="{{post.thumbnail.url}}">
          </a>
          <div class="mt-4">
            <h3 class="text-gray-500 text-xs tracking-widest title-font mb-1">CATEGORY {{post.nombre}}</h3>
            <h2 class="text-gray-900 title-font text-lg font-medium">{{post.descripcion}}</h2>
            <p class="mt-1">$16.00</p>
          </div>
        </div>
        
        {%endfor%}
      </div>
    </div>
  </section>

  
{% endblock content %}



{% block footer %}
{% include 'components/footer.html'%}
{% endblock footer %}



{% block javascript %}{% endblock javascript %}

templates/components/navbar.html
<!-- This example requires Tailwind CSS v2.0+ -->
{% load static %}

<div class="relative bg-white z-10">
    <div class="max-w-7xl mx-auto px-4 sm:px-6">
      <div class="flex justify-between items-center border-b-2 border-gray-100 py-6 md:justify-start md:space-x-10">
        <div class="flex justify-start lg:w-0 lg:flex-1">
          <a href="{% url 'blog:home' %}">
            <span class="sr-only">Workflow</span>
            <img  class="h-8 w-auto sm:h-10" src="https://tailwindui.com/img/logos/workflow-mark-indigo-600.svg" alt="">
            <br>
            <a href="#" class="text-base font-medium text-gray-900 hover:text-gray-700"> Asociacion de Hoteles Morelia </a>
          </a>
        </div>
        
        <nav class="hidden md:flex space-x-10">
          <div class="relative">
            <!-- Item active: "text-gray-900", Item inactive: "text-gray-500" -->
            
  
            <!--
              'Solutions' flyout menu, show/hide based on flyout menu state.
  
              Entering: "transition ease-out duration-200"
                From: "opacity-0 translate-y-1"
                To: "opacity-100 translate-y-0"
              Leaving: "transition ease-in duration-150"
                From: "opacity-100 translate-y-0"
                To: "opacity-0 translate-y-1"
            -->
            
          </div>
  
          <a href="{% url 'blog:home' %}" class="text-base font-medium text-gray-500 hover:text-gray-900"> Home </a>


          <a href="{% url 'blog:hotel' %}" class="text-base font-medium text-gray-500 hover:text-gray-900"> Hoteles </a>
 <!-- #more  evento de click-->
          <div x-data="{open:false}" class="relative">
            <!-- Item active: "text-gray-900", Item inactive: "text-gray-500" -->
            <button @click="open=true" type="button" class="text-gray-500 group bg-white rounded-md inline-flex items-center text-base font-medium hover:text-gray-900 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" aria-expanded="false">
              <span>More</span>
              <!--
                Heroicon name: solid/chevron-down
  
                Item active: "text-gray-600", Item inactive: "text-gray-400"
              -->
              <svg class="text-gray-400 ml-2 h-5 w-5 group-hover:text-gray-500" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
              </svg>
            </button>
  
          

            <div x-show="open" @click.away="open=false" class="absolute z-10 left-1/2 transform -translate-x-1/2 mt-3 px-2 w-screen max-w-md sm:px-0">
              <div class="rounded-lg shadow-lg ring-1 ring-black ring-opacity-5 overflow-hidden">
                <div class="relative grid gap-6 bg-white px-5 py-6 sm:gap-8 sm:p-8">
                  <a href="#" class="-m-3 p-3 flex items-start rounded-lg hover:bg-gray-50">
                    <!-- Heroicon name: outline/support -->
                    <svg class="flex-shrink-0 h-6 w-6 text-indigo-600" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" aria-hidden="true">
                      <path stroke-linecap="round" stroke-linejoin="round" d="M18.364 5.636l-3.536 3.536m0 5.656l3.536 3.536M9.172 9.172L5.636 5.636m3.536 9.192l-3.536 3.536M21 12a9 9 0 11-18 0 9 9 0 0118 0zm-5 0a4 4 0 11-8 0 4 4 0 018 0z" />
                    </svg>
                    <div class="ml-4">
                      <p class="text-base font-medium text-gray-900">Help Center</p>
                      <p class="mt-1 text-sm text-gray-500">Get all of your questions answered in our forums or contact support.</p>
                    </div>
                  </a>
  
                  <a href="#" class="-m-3 p-3 flex items-start rounded-lg hover:bg-gray-50">
                    <!-- Heroicon name: outline/bookmark-alt -->
                    <svg class="flex-shrink-0 h-6 w-6 text-indigo-600" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" aria-hidden="true">
                      <path stroke-linecap="round" stroke-linejoin="round" d="M16 4v12l-4-2-4 2V4M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
                    </svg>
                    <div class="ml-4">
                      <p class="text-base font-medium text-gray-900">Guides</p>
                      <p class="mt-1 text-sm text-gray-500">Learn how to maximize our platform to get the most out of it.</p>
                    </div>
                  </a>
  
                  <a href="#" class="-m-3 p-3 flex items-start rounded-lg hover:bg-gray-50">
                    <!-- Heroicon name: outline/calendar -->
                    <svg class="flex-shrink-0 h-6 w-6 text-indigo-600" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" aria-hidden="true">
                      <path stroke-linecap="round" stroke-linejoin="round" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
                    </svg>
                    <div class="ml-4">
                      <p class="text-base font-medium text-gray-900">Events</p>
                      <p class="mt-1 text-sm text-gray-500">See what meet-ups and other events we might be planning near you.</p>
                    </div>
                  </a>
  
                  <a href="#" class="-m-3 p-3 flex items-start rounded-lg hover:bg-gray-50">
                    <!-- Heroicon name: outline/shield-check -->
                    <svg class="flex-shrink-0 h-6 w-6 text-indigo-600" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" aria-hidden="true">
                      <path stroke-linecap="round" stroke-linejoin="round" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
                    </svg>
                    <div class="ml-4">
                      <p class="text-base font-medium text-gray-900">Security</p>
                      <p class="mt-1 text-sm text-gray-500">Understand how we take your privacy seriously.</p>
                    </div>
                  </a>
                </div>
                
              </div>
            </div>
          </div>
 <!-- #signing -->
    <!--    </nav> 
        <div class="hidden md:flex items-center justify-end md:flex-1 lg:w-0">
          <a href="#" class="whitespace-nowrap text-base font-medium text-gray-500 hover:text-gray-900"> Sign in </a>
          <a href="#" class="ml-8 whitespace-nowrap inline-flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-white bg-indigo-600 hover:bg-indigo-700"> Sign up </a>
        </div>
      </div>
    </div>  -->
 



    <!--
      Mobile menu, show/hide based on mobile menu state.
  
      Entering: "duration-200 ease-out"
        From: "opacity-0 scale-95"
        To: "opacity-100 scale-100"
      Leaving: "duration-100 ease-in"
        From: "opacity-100 scale-100"
        To: "opacity-0 scale-95"
    -->
    <div class="absolute top-0 inset-x-0 p-2 transition transform origin-top-right md:hidden">
      <div class="rounded-lg shadow-lg ring-1 ring-black ring-opacity-5 bg-white divide-y-2 divide-gray-50">
        <div class="pt-5 pb-6 px-5">
          <div class="flex items-center justify-between">
            <div>
              <img class="h-8 w-auto" src="https://tailwindui.com/img/logos/workflow-mark-indigo-600.svg" alt="Workflow">
            </div>
            <div class="-mr-2">
              <button type="button" class="bg-white rounded-md p-2 inline-flex items-center justify-center text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500">
                <span class="sr-only">Close menu</span>
                <!-- Heroicon name: outline/x -->
                <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" aria-hidden="true">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>
          </div>




          <div class="mt-6">
            <nav class="grid gap-y-8">
              <a href="#" class="-m-3 p-3 flex items-center rounded-md hover:bg-gray-50">
                <!-- Heroicon name: outline/chart-bar -->
                <svg class="flex-shrink-0 h-6 w-6 text-indigo-600" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" aria-hidden="true">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
                </svg>
                <span class="ml-3 text-base font-medium text-gray-900"> Analytics </span>
              </a>
  
            </nav>
          </div>
        </div>



        <div class="py-6 px-5 space-y-6">
          <div class="grid grid-cols-2 gap-y-4 gap-x-8">
            <a href="#" class="text-base font-medium text-gray-900 hover:text-gray-700"> Pricing </a>
  
            <a href="#" class="text-base font-medium text-gray-900 hover:text-gray-700"> docs </a>
  
            <a href="#" class="text-base font-medium text-gray-900 hover:text-gray-700"> Help Center </a>
  
            <a href="#" class="text-base font-medium text-gray-900 hover:text-gray-700"> Guides </a>
  
            <a href="#" class="text-base font-medium text-gray-900 hover:text-gray-700"> Events </a>
  
            <a href="#" class="text-base font-medium text-gray-900 hover:text-gray-700"> Security </a>
          </div>
          <div>
            <a href="#" class="w-full flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-white bg-indigo-600 hover:bg-indigo-700"> Sign up </a>
            <p class="mt-6 text-center text-base font-medium text-gray-500">
              Existing customer?
              <a href="#" class="text-indigo-600 hover:text-indigo-500"> Sign in </a>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
  

templates/index.html
{% extends 'base.html' %}

{% block title %}{% endblock title %}

{% block extra_head %}{% endblock extra_head %}


{% block navbar %}
{% include 'components/navbar.html' %}
{% endblock navbar %}


{% block content %}
  
  <!-- This example requires Tailwind CSS v2.0+ -->
  <div>
    <div class="relative bg-gray-50 pt-16 pb-20 px-4 sm:px-6 lg:pt-24 lg:pb-28 lg:px-8">
       <div class="absolute inset-0">
               <div class="bg-white h-1/3 sm:h-2/3">


               </div>
          
             </div>
          <div class="relative max-w-7xl mx-auto">
          <div class="text-center">
           <h2 class="text-3xl tracking-tight font-extrabold text-gray-900 sm:text-4xl">
          Eventos para Realizar
           </h2>
            <p class="mt-3 max-w-2xl mx-auto text-xl text-gray-500 sm:mt-4">
         Aqui vamos a listar las actividades que se pueden realizar en los hoteles
           </p>


         </div>

    </div>
  </div>


<section class="overflow-hidden text-gray-700 ">
  <div class="container px-5 py-2 mx-auto lg:pt-12 lg:px-32">
    <div class="flex flex-wrap -m-1 md:-m-2">

      {%for post in posts%}

      <div class="flex flex-wrap w-1/3">
        <div class="w-full p-1 md:p-2">
          <img alt="gallery" class="block object-cover object-center w-full h-full rounded-lg"
          src="{{post.thumbnail.url}}">
        </div>
        <br>
        
        
      </div>
     
        
      
      <br>
      <br>
      {%endfor%}


    </div>
  </div>
</section>


  


{% endblock content %}



{% block footer %}
{% include 'components/footer.html'%}
{% endblock footer %}



{% block javascript %}{% endblock javascript %}

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-grey-lightest font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>